---
title: "Marriages in Toronto before and after the pandemic"
subtitle: "My subtitle if needed"
author: 
  - Xinxiang Gao
thanks: "Code and data are available at: https://github.com/xgao28/Marriage-Licence-Statistics"
date: today
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)

data <- read_csv("../data/analysis_data/analysis_data.csv")
```

@opendatatoronto, @citeR, @rohan

```{r}
#| label: fig-date
#| fig-cap: Number of marriage licenses over time
#| echo: false

ggplot(data, aes(x = date, y = marriage_licenses)) +
  # geom_line(color = "#2C3E50", size = 1.2, alpha = 0.8) +  # Thicker line, custom color
  geom_point(color = "#E74C3C", size = 2, alpha = 0.8) +   # Add points for better visibility
  labs(
    title = "Number of Marriage Licenses Over Time",
    subtitle = "An overview of trends in marriage licenses issued",
    x = "Date",
    y = "Number of Marriage Licenses"
  ) + 
  theme_minimal()
```



\newpage


# References


